### ISSUE TITLE
Keymaps require all options set when submodule used

### ISSUE THREAD

**Issue by dfangx** [NixNeovim/NixNeovim#71] opened 2023-07-18 22:46 UTC
When defining a key map like:
```
mappings.normal."<leader>h" = { silent = true; action = "'<c-w>H'"; };
````
the following error is thrown by home-manager:
```
warning: Git tree '/home/cyrusng/nixos-config' is dirty
error:
       … while evaluating a branch condition

         at /nix/store/3j9garb3574mxikwbi6zn594j8mjd19s-source/lib/lists.nix:57:9:

           56|       fold' = n:
           57|         if n == len
             |         ^
           58|         then nul

       … while calling the 'length' builtin

         at /nix/store/3j9garb3574mxikwbi6zn594j8mjd19s-source/lib/lists.nix:55:13:

           54|     let
           55|       len = length list;
             |             ^
           56|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: value is null while a Boolean was expecte
```
When all mapping options are defined, the error does not occur. The defaults as mentioned in the README don't seem to be honored.

**Comment by jooooscha** [comment] 2023-07-19 09:00
I cannot reproduce this on my system. I added your example, but it builds without errors.

Are you on the newest commit?
Could you give me your compltete NixNeovim config?

**Comment by VincentBerthier** [comment] 2023-08-01 17:08
The problem comes from the "usePluginDefaults = true;" option.
Without it, no problem, but with it I have the same error.

**Comment by jooooscha** [comment] 2023-08-05 10:08
Ok, with `usePluginDefaults = true` I got a similar but different error on running `nix flake check`. I have pushed a fix. Please report back if that has solved your problem, as well

**Comment by VincentBerthier** [comment] 2023-08-05 10:54
It doesn’t look like it does (on my side at least), same error.

**Comment by jooooscha** [comment] 2023-08-06 15:21
mh, ok. I will look into it

**Comment by jooooscha** [comment] 2023-09-06 17:41
Could you check, if #75 solves your problem?
It is a huge internal refactor, but as far as I can tell it incidentally also solved this problem for me.

Please report if you still have any problems

**Comment by VincentBerthier** [comment] 2023-09-08 14:06
Hi,
It seems to be working fine now indeed, thanks.

**Closed** 2023-09-08 20:58 UTC
